services:
  backend:
    build: ./
    working_dir: /GoCode
    container_name: backend
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"
    command:
      - ./commands/start_server.sh
    volumes:
      - ./src:/GoCode/src
      - ./commands:/GoCode/commands
      - ./.env:/GoCode/.env
    env_file:
      - .env

  postgres:
    image: postgres:16.4
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/Lib/postgresql/data
    restart: on-failure
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:4.0-alpine
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  redis:
    image: redis:7.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    depends_on:
      - backend
      - rabbitmq
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis

volumes:
  pg_data: { }
  rabbitmq: { }
  redis: { }
