name: backend CI

on:
  - push
  - pull_request

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_FROM: ${{ secrets.MAIL_FROM }}
  MAIL_PORT: ${{ secrets.MAIL_PORT }}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
  DB_URL: ${{ secrets.DB_URL }}
  RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migrations
      run: |
        cd src
        alembic upgrade head
    - name: Testing endpoints
      run: |
        pytest src/tests/